name: Test localgovdrupal drupal-module

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    uses: millnut/localgov_shared_workflows/.github/workflows/test.yml@main
    with:
      project: 'localgovdrupal/localgov_alert_banner'
      project_path: 'web/modules/contrib/localgov_alert_banner'